h3:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100 #100  
  
  # Position Controllers ---------------------------------------
  right_hip_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_hip
    pid: {p: 480.0, i: 5.71, d: 0.3571, i_clamp: 100}
  right_knee_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_knee
    pid: {p: 0.0, i: 0, d: 0, i_clamp: 100}
  right_ankle_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_ankle
    pid: {p: 480.0, i: 5.71, d: 0.3571, i_clamp: 100}
  left_hip_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_hip
    pid: {p: 480.0, i: 5.71, d: 0.3571, i_clamp: 100}
  left_knee_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_knee
    pid: {p: 480.0, i: 5.71, d: 0.3571, i_clamp: 100}
  left_ankle_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_ankle
    pid: {p: 480.0, i: 5.71, d: 0.3571, i_clamp: 100}
  robot_config_controller:
    type: h3_config_controller/H3ConfigController 
    robot_name: exo_h3
    control_type: [6, 6, 6, 6, 6, 6]
    min_angle: [-1.7453, 0, -0.4363, -1.7453, 0, -0.4363]
    max_angle: [0.4363, 1.7453, 0.4363, 0.4363, 1.7453, 0.4363]
    assistance: [50, 50, 50, 50, 50, 50]
  robot_state_controller:
    type: h3_robot_state_controller/H3RobotStateController
    robot_name: exo_h3
    publish_rate: 100

  